todo/urls.py
from django.urls import path

from todo.views import (
    TodoListView,
    TagsListView,
    TodoCreateView,
    TodoUpdateView,
    TodoDeleteView,
    TagsCreateView,
    TagsUpdateView,
    TagsDeleteView,
    ChangeFinishedViewStatus
)

urlpatterns = [
    path("", TodoListView.as_view(), name="index"),
    path("todo/create/", TodoCreateView.as_view(), name="todo_create"),
    path(
        "todo/<int:pk>/update/",
        TodoUpdateView.as_view(),
        name="todo_update"
    ),
    path(
        "todo/<int:pk>/delete/",
        TodoDeleteView.as_view(),
        name="todo_delete"
    ),
    path(
        "todo/<int:pk>/status/",
        ChangeFinishedViewStatus.as_view(),
        name="status_update"
    ),
    path("tags/", TagsListView.as_view(), name="tags"),
    path("tags/create/", TagsCreateView.as_view(), name="tags_create"),
    path(
        "tags/<int:pk>/update/",
        TagsUpdateView.as_view(),
        name="tags_update"
    ),
    path("tags/<int:pk>/delete/", TagsDeleteView.as_view(), name="tags_delete")
]

app_name = "todo"

todobase/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("todo.urls", "todo"))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todo/models.py
import datetime

from django.db import models


class Tags(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.TextField()
    date = models.DateTimeField(default=datetime.date.today)
    finished = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tags, related_name='tasks')

    def __str__(self):
        return self.content

todo/views.py
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from todo.models import Task, Tags


class TodoListView(ListView):
    model = Task
    context_object_name = 'tasks'
    paginate_by = 5
    template_name = "todo/index.html"


class TodoCreateView(CreateView):
    model = Task
    fields = ("content", "tags")
    success_url = reverse_lazy("todo:index")


class TodoUpdateView(UpdateView):
    model = Task
    fields = ("content", "tags")
    success_url = reverse_lazy("todo:index")


class TodoDeleteView(DeleteView):
    model = Task
    success_url = reverse_lazy("todo:index")


class TagsListView(ListView):
    model = Tags
    context_object_name = 'tags'
    paginate_by = 5


class TagsCreateView(CreateView):
    model = Tags
    fields = "__all__"
    success_url = reverse_lazy("todo:tags")


class TagsUpdateView(UpdateView):
    model = Tags
    fields = "__all__"
    success_url = reverse_lazy("todo:tags")


class TagsDeleteView(DeleteView):
    model = Tags


class ChangeFinishedViewStatus(View):
    def post(self, request, *args, **kwargs):
        pk = kwargs.get("pk")
        task = Task.objects.get(pk=pk)
        task.finished = not task.finished
        task.save()
        return redirect("todo:index")

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>Restaurant</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">
          {% block sidebar %}
            {% include "includes/sidebar.html" %}
          {% endblock %}
        </div>
        <div class="col-sm-10 ">

            {% block content %}{% endblock %}

            {% block pagination %}
                {% include "includes/pagination.html" %}
            {% endblock %}

        </div>
    </div>
</div>
</body>

</html>

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'todo:index' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'todo:tags' %}">Tags</a></li>
</ul>

templates/todo/index.html
{% extends "base.html" %}

{% block content %}
<h1>Todo list</h1>
<a href="{% url 'todo:todo_create' %}" class="top-right-position btn btn-primary">Add task</a>
<ul>
    {% for task in tasks %}
    <li>
        <ul>
        <li><b>{{ task.content }}
            {% if task.finished %}<span style="color: green">Done</span>
            {% else %} <span style="color: red">Not done</span>
            {% endif %}
            </b>
            {% if task.finished %}
            <form action="{% url 'todo:status_update' pk=task.pk %}" method="POST">
                {% csrf_token %}
                <button class="btn btn-secondary">Undo</button>
            </form>
            {% else %}
            <form action="{% url 'todo:status_update' pk=task.pk %}" method="POST">
                {% csrf_token %}
                <button class="btn btn-success">Complete</button>
            </form>
            {% endif %}


        </li>
        <li>Created: {{task.date|date:"F j, Y, g:i a"}}</li>
        <li>Tags: {% for tag in task.tags.all %} {{tag.name}} {% endfor %} <a href="{% url 'todo:todo_update' pk=task.pk %}">Update</a> <a href="{% url 'todo:todo_delete' pk=task.pk %}">Delete</a></li>
        </ul>
    </li>
    {% endfor %}
</ul>
{% endblock %}

templates/todo/tags_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete Task?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/todo/tags_form.html
{% extends "base.html" %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Task</h1>
<form action="" method="post" novalidate>
    {{ form.error }}
    {% csrf_token %}
    {{ form }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/todo/tags_list.html
{% extends "base.html" %}

{% block content %}
    <h1>Tags</h1>
    <a href="{% url 'todo:tags_create' %}" class="top-right-position btn btn-primary">Add</a>
    <table class="table table-hover">
        <tr>
            <th>
                <b>Name</b>
            </th>
            <th>
                <b>Update</b>
            </th>
            <th>
                <b>Delete</b>
            </th>
        </tr>
        {% for tag in tags %}
        <tr>
            <th>
                {{ tag.name }}
            </th>
            <th>
                <a href="{% url 'todo:tags_update' pk=tag.pk%}" class="btn btn-secondary">Update</a>
            </th>
            <th>
                <a href="{% url 'todo:tags_delete' pk=tag.pk%}" class="btn btn-secondary">Delete</a>
            </th>
        </tr>
        {% endfor %}
    </table>
{% endblock %}

templates/todo/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete Task?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/todo/task_form.html
{% extends "base.html" %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Task</h1>
<form action="" method="post" novalidate>
    {{ form.error }}
    {% csrf_token %}
    {{ form }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}